# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TuneShare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TuneShare
  pod 'Parse'
  pod 'AlamofireImage'
  pod 'MessageInputBar'
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'TuneShareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TuneShareUITests' do
    # Pods for testing
  end

end
